//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainStreetMarketDatabaseEntities : DbContext
    {
        public MainStreetMarketDatabaseEntities()
            : base("name=MainStreetMarketDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category_Tbl> Category_Tbl { get; set; }
        public virtual DbSet<Product_Tbl> Product_Tbl { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
    }
}
