//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Tbl
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubCategory_Id { get; set; }
        public string Description { get; set; }
        public string ProductImage { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Category_Tbl Category_Tbl { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
